const SET_DATA = 'SET_DATA';
const SET_SELECTED_ROOM = 'SET_SELECTED_ROOM';
const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
const CLEAR_DATA = 'CLEAR_DATA';

export { SET_DATA, SET_SELECTED_ROOM, UPDATE_ACTIVITY, CLEAR_DATA };
